"""Utility functions and classes for OpenAlex client."""

from ..constants import (
    DOI_URL_PREFIX,
    MAG_PREFIX,
    OPENALEX_ID_PREFIX,
    ORCID_URL_PREFIX,
    PMID_PREFIX,
)
from .batch import chunk_list
from .common import (
    empty_list_result,
    ensure_prefix,
    extract_entity_type,
    id_to_url,
    ids_equal,
    is_openalex_id,
    normalize_entity_id,
    normalize_id_batch,
    parse_entity_ids,
    strip_id_prefix,
    validate_id_format,
)
from .pagination import AsyncPaginator, Paginator
from .params import normalize_params
from .rate_limit import (
    AsyncRateLimiter,
    RateLimiter,
    SlidingWindowRateLimiter,
    async_rate_limited,
    rate_limited,
)
from .retry import (
    RetryConfig,
    RetryContext,
    RetryHandler,
    async_with_retry,
    constant_backoff,
    exponential_backoff,
    is_retryable_error,
    linear_backoff,
    retry_on_error,
    retry_with_rate_limit,
    with_retry,
)
from .text import (
    clean_html,
    clean_title,
    count_words,
    detect_language,
    extract_doi,
    extract_keywords,
    invert_abstract,
    normalize_author_name,
    truncate_abstract,
)
from .validation import validate_entity_id

__all__ = [
    "DOI_URL_PREFIX",
    "MAG_PREFIX",
    "OPENALEX_ID_PREFIX",
    "ORCID_URL_PREFIX",
    "PMID_PREFIX",
    "AsyncPaginator",
    "AsyncRateLimiter",
    "Paginator",
    "RateLimiter",
    "RetryConfig",
    "RetryContext",
    "RetryHandler",
    "SlidingWindowRateLimiter",
    "async_rate_limited",
    "async_with_retry",
    "chunk_list",
    "clean_html",
    "clean_title",
    "constant_backoff",
    "count_words",
    "detect_language",
    "empty_list_result",
    "ensure_prefix",
    "exponential_backoff",
    "extract_doi",
    "extract_entity_type",
    "extract_keywords",
    "id_to_url",
    "ids_equal",
    "invert_abstract",
    "is_openalex_id",
    "is_retryable_error",
    "linear_backoff",
    "normalize_author_name",
    "normalize_entity_id",
    "normalize_id_batch",
    "normalize_params",
    "parse_entity_ids",
    "rate_limited",
    "retry_on_error",
    "retry_with_rate_limit",
    "strip_id_prefix",
    "truncate_abstract",
    "validate_entity_id",
    "validate_id_format",
    "with_retry",
]
