"""OpenAlex data models."""

from .author import Author, AuthorAffiliation, AuthorIds
from .base import (
    AutocompleteResult,
    CountsByYear,
    DehydratedEntity,
    EntityType,
    Geo,
    GroupByResult,
    InternationalNames,
    ListResult,
    Meta,
    OpenAlexBase,
    OpenAlexEntity,
    Role,
    SummaryStats,
)
from .concept import Concept, ConceptAncestor, ConceptIds, RelatedConcept
from .filters import (
    AuthorsFilter,
    BaseFilter,
    ConceptsFilter,
    FundersFilter,
    GroupBy,
    InstitutionsFilter,
    PublishersFilter,
    SortOrder,
    SourcesFilter,
    WorksFilter,
)
from .funder import Funder, FunderIds
from .institution import (
    AssociatedInstitution,
    Institution,
    InstitutionIds,
    InstitutionTopic,
    InstitutionTopicShare,
    InstitutionType,
    Repository,
)
from .keyword import Keyword
from .publisher import Publisher, PublisherIds
from .source import APCPrice, Society, Source, SourceIds, SourceType
from .topic import Topic, TopicHierarchy, TopicIds, TopicLevel
from .work import (
    APC,
    Authorship,
    Biblio,
    CitationNormalizedPercentile,
    DehydratedAuthor,
    DehydratedConcept,
    DehydratedInstitution,
    DehydratedSource,
    DehydratedTopic,
    Grant,
    KeywordTag,
    Location,
    MeshTag,
    OpenAccess,
    OpenAccessStatus,
    SustainableDevelopmentGoal,
    Work,
    WorkIds,
    WorkType,
)

__all__ = [
    "APC",
    "APCPrice",
    "AssociatedInstitution",
    "Author",
    "AuthorAffiliation",
    "AuthorIds",
    "AuthorsFilter",
    "Authorship",
    "AutocompleteResult",
    "BaseFilter",
    "Biblio",
    "CitationNormalizedPercentile",
    "Concept",
    "ConceptAncestor",
    "ConceptIds",
    "ConceptsFilter",
    "CountsByYear",
    "DehydratedAuthor",
    "DehydratedConcept",
    "DehydratedEntity",
    "DehydratedInstitution",
    "DehydratedSource",
    "DehydratedTopic",
    "EntityType",
    "Funder",
    "FunderIds",
    "FundersFilter",
    "Geo",
    "Grant",
    "GroupBy",
    "GroupByResult",
    "Institution",
    "InstitutionIds",
    "InstitutionTopic",
    "InstitutionTopicShare",
    "InstitutionType",
    "InstitutionsFilter",
    "InternationalNames",
    "Keyword",
    "KeywordTag",
    "ListResult",
    "Location",
    "MeshTag",
    "Meta",
    "OpenAccess",
    "OpenAccessStatus",
    "OpenAlexBase",
    "OpenAlexEntity",
    "Publisher",
    "PublisherIds",
    "PublishersFilter",
    "RelatedConcept",
    "Repository",
    "Role",
    "Society",
    "SortOrder",
    "Source",
    "SourceIds",
    "SourceType",
    "SourcesFilter",
    "SummaryStats",
    "SustainableDevelopmentGoal",
    "Topic",
    "TopicHierarchy",
    "TopicIds",
    "TopicLevel",
    "Work",
    "WorkIds",
    "WorkType",
    "WorksFilter",
]
