"""
OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import unittest

from openalex_python.api.works_api import WorksApi


class TestWorksApi(unittest.TestCase):
    """WorksApi unit test stubs"""

    def setUp(self):
        self.api = WorksApi()

    def tearDown(self):
        pass

    def test_works_get(self):
        """Test case for works_get
        List works
        """
        pass

    def test_works_id_get(self):
        """Test case for works_id_get
        Get a single work
        """
        pass

    def test_works_random_get(self):
        """Test case for works_random_get
        Get a random work
        """
        pass


if __name__ == "__main__":
    unittest.main()
