"""
OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import unittest

from swagger_client.api.autocomplete_api import AutocompleteApi


class TestAutocompleteApi(unittest.TestCase):
    """AutocompleteApi unit test stubs"""

    def setUp(self):
        self.api = AutocompleteApi()

    def tearDown(self):
        pass

    def test_autocomplete_authors_get(self):
        """Test case for autocomplete_authors_get
        Autocomplete for authors
        """
        pass

    def test_autocomplete_concepts_get(self):
        """Test case for autocomplete_concepts_get
        Autocomplete for concepts
        """
        pass

    def test_autocomplete_funders_get(self):
        """Test case for autocomplete_funders_get
        Autocomplete for funders
        """
        pass

    def test_autocomplete_get(self):
        """Test case for autocomplete_get
        Autocomplete across all entity types
        """
        pass

    def test_autocomplete_institutions_get(self):
        """Test case for autocomplete_institutions_get
        Autocomplete for institutions
        """
        pass

    def test_autocomplete_publishers_get(self):
        """Test case for autocomplete_publishers_get
        Autocomplete for publishers
        """
        pass

    def test_autocomplete_sources_get(self):
        """Test case for autocomplete_sources_get
        Autocomplete for sources
        """
        pass

    def test_autocomplete_works_get(self):
        """Test case for autocomplete_works_get
        Autocomplete for works
        """
        pass


if __name__ == "__main__":
    unittest.main()
