"""
OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import unittest

from openalex_python.api.authors_api import AuthorsApi


class TestAuthorsApi(unittest.TestCase):
    """AuthorsApi unit test stubs"""

    def setUp(self):
        self.api = AuthorsApi()

    def tearDown(self):
        pass

    def test_authors_get(self):
        """Test case for authors_get
        List authors
        """
        pass

    def test_authors_id_get(self):
        """Test case for authors_id_get
        Get a single author
        """
        pass

    def test_authors_random_get(self):
        """Test case for authors_random_get
        Get a random author
        """
        pass

    def test_people_get(self):
        """Test case for people_get
        List people (alias for authors)
        """
        pass

    def test_people_id_get(self):
        """Test case for people_id_get
        Get a single person (alias for author)
        """
        pass


if __name__ == "__main__":
    unittest.main()
