"""
OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import unittest

from swagger_client.api.concepts_api import ConceptsApi


class TestConceptsApi(unittest.TestCase):
    """ConceptsApi unit test stubs"""

    def setUp(self):
        self.api = ConceptsApi()

    def tearDown(self):
        pass

    def test_concepts_get(self):
        """Test case for concepts_get
        List concepts
        """
        pass

    def test_concepts_id_get(self):
        """Test case for concepts_id_get
        Get a single concept
        """
        pass

    def test_concepts_random_get(self):
        """Test case for concepts_random_get
        Get a random concept
        """
        pass


if __name__ == "__main__":
    unittest.main()
