"""
OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import unittest

from openalex_python.api.institutions_api import InstitutionsApi


class TestInstitutionsApi(unittest.TestCase):
    """InstitutionsApi unit test stubs"""

    def setUp(self):
        self.api = InstitutionsApi()

    def tearDown(self):
        pass

    def test_institutions_get(self):
        """Test case for institutions_get
        List institutions
        """
        pass

    def test_institutions_id_get(self):
        """Test case for institutions_id_get
        Get a single institution
        """
        pass

    def test_institutions_random_get(self):
        """Test case for institutions_random_get
        Get a random institution
        """
        pass


if __name__ == "__main__":
    unittest.main()
