from swagger_client.api.authors_api import AuthorsApi
from swagger_client.api.autocomplete_api import AutocompleteApi
from swagger_client.api.concepts_api import ConceptsApi
from swagger_client.api.funders_api import FundersApi
from swagger_client.api.general_api import GeneralApi
from swagger_client.api.institutions_api import InstitutionsApi
from swagger_client.api.keywords_api import KeywordsApi
from swagger_client.api.publishers_api import PublishersApi
from swagger_client.api.sources_api import SourcesApi
from swagger_client.api.text_api import TextApi
from swagger_client.api.topics_api import TopicsApi
from swagger_client.api.works_api import WorksApi
