"""OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git.
"""

from openalex_python.api.authors_api import AuthorsApi
from openalex_python.api.autocomplete_api import AutocompleteApi
from openalex_python.api.concepts_api import ConceptsApi
from openalex_python.api.funders_api import FundersApi
from openalex_python.api.general_api import GeneralApi
from openalex_python.api.institutions_api import InstitutionsApi
from openalex_python.api.keywords_api import KeywordsApi
from openalex_python.api.publishers_api import PublishersApi
from openalex_python.api.sources_api import SourcesApi
from openalex_python.api.text_api import TextApi
from openalex_python.api.topics_api import TopicsApi
from openalex_python.api.works_api import WorksApi
from openalex_python.api_client import ApiClient
from openalex_python.configuration import Configuration
from openalex_python.models import *
