"""OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git.
"""

from openalex_python.api.authors_api import AuthorsApi
from openalex_python.api.autocomplete_api import AutocompleteApi
from openalex_python.api.concepts_api import ConceptsApi
from openalex_python.api.funders_api import FundersApi
from openalex_python.api.general_api import GeneralApi
from openalex_python.api.institutions_api import InstitutionsApi
from openalex_python.api.keywords_api import KeywordsApi
from openalex_python.api.publishers_api import PublishersApi
from openalex_python.api.sources_api import SourcesApi
from openalex_python.api.text_api import TextApi
from openalex_python.api.topics_api import TopicsApi
from openalex_python.api.works_api import WorksApi
from openalex_python.api_client import ApiClient
from openalex_python.configuration import Configuration
from openalex_python.models.all_of_text_concepts_results_concepts_items import (
    AllOfTextConceptsResultsConceptsItems,
)
from openalex_python.models.all_of_text_results_concepts_items import (
    AllOfTextResultsConceptsItems,
)
from openalex_python.models.all_of_text_results_topics_items import (
    AllOfTextResultsTopicsItems,
)
from openalex_python.models.all_of_text_topics_results_topics_items import (
    AllOfTextTopicsResultsTopicsItems,
)
from openalex_python.models.apc import APC
from openalex_python.models.associated_institution import AssociatedInstitution
from openalex_python.models.author import Author
from openalex_python.models.author_affiliations import AuthorAffiliations
from openalex_python.models.author_ids import AuthorIds
from openalex_python.models.authors_list import AuthorsList
from openalex_python.models.authorship import Authorship
from openalex_python.models.authorship_affiliations import AuthorshipAffiliations
from openalex_python.models.autocomplete_result import AutocompleteResult
from openalex_python.models.autocomplete_results import AutocompleteResults
from openalex_python.models.biblio import Biblio
from openalex_python.models.concept import Concept
from openalex_python.models.concept_ids import ConceptIds
from openalex_python.models.concepts_list import ConceptsList
from openalex_python.models.counts_by_year import CountsByYear
from openalex_python.models.counts_by_year_inner import CountsByYearInner
from openalex_python.models.dehydrated_author import DehydratedAuthor
from openalex_python.models.dehydrated_concept import DehydratedConcept
from openalex_python.models.dehydrated_funder import DehydratedFunder
from openalex_python.models.dehydrated_institution import DehydratedInstitution
from openalex_python.models.dehydrated_publisher import DehydratedPublisher
from openalex_python.models.dehydrated_source import DehydratedSource
from openalex_python.models.dehydrated_topic import DehydratedTopic
from openalex_python.models.error_response import ErrorResponse
from openalex_python.models.funder import Funder
from openalex_python.models.funder_ids import FunderIds
from openalex_python.models.funders_list import FundersList
from openalex_python.models.geo import Geo
from openalex_python.models.grant import Grant
from openalex_python.models.group_by_result import GroupByResult
from openalex_python.models.group_by_result_inner import GroupByResultInner
from openalex_python.models.institution import Institution
from openalex_python.models.institution_ids import InstitutionIds
from openalex_python.models.institutions_list import InstitutionsList
from openalex_python.models.international_names import InternationalNames
from openalex_python.models.keyword import Keyword
from openalex_python.models.keyword_tag import KeywordTag
from openalex_python.models.keywords_list import KeywordsList
from openalex_python.models.location import Location
from openalex_python.models.mesh_tag import MeshTag
from openalex_python.models.meta import Meta
from openalex_python.models.open_access import OpenAccess
from openalex_python.models.publisher import Publisher
from openalex_python.models.publisher_ids import PublisherIds
from openalex_python.models.publishers_list import PublishersList
from openalex_python.models.repository import Repository
from openalex_python.models.role import Role
from openalex_python.models.root_response import RootResponse
from openalex_python.models.source import Source
from openalex_python.models.source_apc_prices import SourceApcPrices
from openalex_python.models.source_ids import SourceIds
from openalex_python.models.source_societies import SourceSocieties
from openalex_python.models.sources_list import SourcesList
from openalex_python.models.summary_stats import SummaryStats
from openalex_python.models.sustainable_development_goal import (
    SustainableDevelopmentGoal,
)
from openalex_python.models.text_body import TextBody
from openalex_python.models.text_concepts_results import TextConceptsResults
from openalex_python.models.text_concepts_results_meta import TextConceptsResultsMeta
from openalex_python.models.text_keyword import TextKeyword
from openalex_python.models.text_keywords_results import TextKeywordsResults
from openalex_python.models.text_keywords_results_meta import TextKeywordsResultsMeta
from openalex_python.models.text_meta import TextMeta
from openalex_python.models.text_results import TextResults
from openalex_python.models.text_topics_results import TextTopicsResults
from openalex_python.models.text_topics_results_meta import TextTopicsResultsMeta
from openalex_python.models.topic import Topic
from openalex_python.models.topic_ids import TopicIds
from openalex_python.models.topic_level import TopicLevel
from openalex_python.models.topics_list import TopicsList
from openalex_python.models.work import Work
from openalex_python.models.work_citation_normalized_percentile import (
    WorkCitationNormalizedPercentile,
)
from openalex_python.models.work_ids import WorkIds
from openalex_python.models.works_list import WorksList
