"""OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git.
"""

from swagger_client.models.all_of_text_concepts_results_concepts_items import (
    AllOfTextConceptsResultsConceptsItems,
)
from swagger_client.models.all_of_text_results_concepts_items import (
    AllOfTextResultsConceptsItems,
)
from swagger_client.models.all_of_text_results_topics_items import (
    AllOfTextResultsTopicsItems,
)
from swagger_client.models.all_of_text_topics_results_topics_items import (
    AllOfTextTopicsResultsTopicsItems,
)
from swagger_client.models.apc import APC
from swagger_client.models.associated_institution import AssociatedInstitution
from swagger_client.models.author import Author
from swagger_client.models.author_affiliations import AuthorAffiliations
from swagger_client.models.author_ids import AuthorIds
from swagger_client.models.authors_list import AuthorsList
from swagger_client.models.authorship import Authorship
from swagger_client.models.authorship_affiliations import AuthorshipAffiliations
from swagger_client.models.autocomplete_result import AutocompleteResult
from swagger_client.models.autocomplete_results import AutocompleteResults
from swagger_client.models.biblio import Biblio
from swagger_client.models.concept import Concept
from swagger_client.models.concept_ids import ConceptIds
from swagger_client.models.concepts_list import ConceptsList
from swagger_client.models.counts_by_year import CountsByYear
from swagger_client.models.counts_by_year_inner import CountsByYearInner
from swagger_client.models.dehydrated_author import DehydratedAuthor
from swagger_client.models.dehydrated_concept import DehydratedConcept
from swagger_client.models.dehydrated_funder import DehydratedFunder
from swagger_client.models.dehydrated_institution import DehydratedInstitution
from swagger_client.models.dehydrated_publisher import DehydratedPublisher
from swagger_client.models.dehydrated_source import DehydratedSource
from swagger_client.models.dehydrated_topic import DehydratedTopic
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.funder import Funder
from swagger_client.models.funder_ids import FunderIds
from swagger_client.models.funders_list import FundersList
from swagger_client.models.geo import Geo
from swagger_client.models.grant import Grant
from swagger_client.models.group_by_result import GroupByResult
from swagger_client.models.group_by_result_inner import GroupByResultInner
from swagger_client.models.institution import Institution
from swagger_client.models.institution_ids import InstitutionIds
from swagger_client.models.institutions_list import InstitutionsList
from swagger_client.models.international_names import InternationalNames
from swagger_client.models.keyword import Keyword
from swagger_client.models.keyword_tag import KeywordTag
from swagger_client.models.keywords_list import KeywordsList
from swagger_client.models.location import Location
from swagger_client.models.mesh_tag import MeshTag
from swagger_client.models.meta import Meta
from swagger_client.models.open_access import OpenAccess
from swagger_client.models.publisher import Publisher
from swagger_client.models.publisher_ids import PublisherIds
from swagger_client.models.publishers_list import PublishersList
from swagger_client.models.repository import Repository
from swagger_client.models.role import Role
from swagger_client.models.root_response import RootResponse
from swagger_client.models.source import Source
from swagger_client.models.source_apc_prices import SourceApcPrices
from swagger_client.models.source_ids import SourceIds
from swagger_client.models.source_societies import SourceSocieties
from swagger_client.models.sources_list import SourcesList
from swagger_client.models.summary_stats import SummaryStats
from swagger_client.models.sustainable_development_goal import (
    SustainableDevelopmentGoal,
)
from swagger_client.models.text_body import TextBody
from swagger_client.models.text_concepts_results import TextConceptsResults
from swagger_client.models.text_concepts_results_meta import TextConceptsResultsMeta
from swagger_client.models.text_keyword import TextKeyword
from swagger_client.models.text_keywords_results import TextKeywordsResults
from swagger_client.models.text_keywords_results_meta import TextKeywordsResultsMeta
from swagger_client.models.text_meta import TextMeta
from swagger_client.models.text_results import TextResults
from swagger_client.models.text_topics_results import TextTopicsResults
from swagger_client.models.text_topics_results_meta import TextTopicsResultsMeta
from swagger_client.models.topic import Topic
from swagger_client.models.topic_ids import TopicIds
from swagger_client.models.topic_level import TopicLevel
from swagger_client.models.topics_list import TopicsList
from swagger_client.models.work import Work
from swagger_client.models.work_citation_normalized_percentile import (
    WorkCitationNormalizedPercentile,
)
from swagger_client.models.work_ids import WorkIds
from swagger_client.models.works_list import WorksList
