"""Expose models from the OpenAlex API client."""
from __future__ import annotations

from .author import (
    Author,
    AuthorAffiliations,
    AuthorIds,
    AuthorsList,
    Authorship,
    AuthorshipAffiliations,
    DehydratedAuthor,
)
from .concept import (
    Concept,
    ConceptIds,
    ConceptsList,
    DehydratedConcept,
)
from .funder import Funder, FunderIds, FundersList, DehydratedFunder
from .institution import (
    Institution,
    Repository,
    AssociatedInstitution,
    DehydratedInstitution,
    InstitutionIds,
    InstitutionsList,
)
from .keyword import Keyword, KeywordsList
from .publisher import (
    Publisher,
    PublisherIds,
    PublishersList,
    DehydratedPublisher,
)
from .source import (
    Source,
    SourceApcPrices,
    SourceIds,
    SourceSocieties,
    SourcesList,
    DehydratedSource,
)
from .topic import (
    Topic,
    TopicIds,
    TopicLevel,
    TopicsList,
    DehydratedTopic,
)
from .work import (
    Work,
    WorksList,
    WorkIds,
    WorkCitationNormalizedPercentile,
    Biblio,
    Location,
    MeshTag,
    KeywordTag,
    Grant,
    OpenAccess,
    SustainableDevelopmentGoal,
    APC,
)
from .autocomplete import AutocompleteResult, AutocompleteResults
from .text import (
    TextBody,
    AllOfTextConceptsResultsConceptsItems,
    AllOfTextResultsConceptsItems,
    AllOfTextResultsTopicsItems,
    AllOfTextTopicsResultsTopicsItems,
    TextConceptsResults,
    TextConceptsResultsMeta,
    TextKeyword,
    TextKeywordsResults,
    TextKeywordsResultsMeta,
    TextMeta,
    TextResults,
    TextTopicsResults,
    TextTopicsResultsMeta,
)
from .general import RootResponse
from .common import (
    CountsByYear,
    CountsByYearInner,
    ErrorResponse,
    Geo,
    GroupByResult,
    GroupByResultInner,
    InternationalNames,
    Meta,
    Role,
    SummaryStats,
)

__all__ = [
    "APC",
    "AllOfTextConceptsResultsConceptsItems",
    "AllOfTextResultsConceptsItems",
    "AllOfTextResultsTopicsItems",
    "AllOfTextTopicsResultsTopicsItems",
    "AssociatedInstitution",
    "Author",
    "AuthorAffiliations",
    "AuthorIds",
    "AuthorsList",
    "Authorship",
    "AuthorshipAffiliations",
    "AutocompleteResult",
    "AutocompleteResults",
    "Biblio",
    "Concept",
    "ConceptIds",
    "ConceptsList",
    "CountsByYear",
    "CountsByYearInner",
    "DehydratedAuthor",
    "DehydratedConcept",
    "DehydratedFunder",
    "DehydratedInstitution",
    "DehydratedPublisher",
    "DehydratedSource",
    "DehydratedTopic",
    "ErrorResponse",
    "Funder",
    "FunderIds",
    "FundersList",
    "Geo",
    "Grant",
    "GroupByResult",
    "GroupByResultInner",
    "Institution",
    "InstitutionIds",
    "InstitutionsList",
    "InternationalNames",
    "Keyword",
    "KeywordTag",
    "KeywordsList",
    "Location",
    "MeshTag",
    "Meta",
    "OpenAccess",
    "Publisher",
    "PublisherIds",
    "PublishersList",
    "Repository",
    "Role",
    "RootResponse",
    "Source",
    "SourceApcPrices",
    "SourceIds",
    "SourceSocieties",
    "SourcesList",
    "SummaryStats",
    "SustainableDevelopmentGoal",
    "TextBody",
    "TextConceptsResults",
    "TextConceptsResultsMeta",
    "TextKeyword",
    "TextKeywordsResults",
    "TextKeywordsResultsMeta",
    "TextMeta",
    "TextResults",
    "TextTopicsResults",
    "TextTopicsResultsMeta",
    "Topic",
    "TopicIds",
    "TopicLevel",
    "TopicsList",
    "Work",
    "WorkCitationNormalizedPercentile",
    "WorkIds",
    "WorksList",
]
