"""OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git.
"""

import pprint

import six


class AuthorAffiliations:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"institution": "DehydratedInstitution", "years": "list[int]"}
    attribute_map = {"institution": "institution", "years": "years"}

    def __init__(self, institution=None, years=None):
        """AuthorAffiliations - a model defined in Swagger."""
        self._institution = None
        self._years = None
        self.discriminator = None
        self.institution = institution
        self.years = years

    @property
    def institution(self):
        """Gets the institution of this AuthorAffiliations.
        :return: The institution of this AuthorAffiliations.
        :rtype: DehydratedInstitution.
        """
        return self._institution

    @institution.setter
    def institution(self, institution):
        """Sets the institution of this AuthorAffiliations.
        :param institution: The institution of this AuthorAffiliations.
        :type: DehydratedInstitution.
        """
        if institution is None:
            raise ValueError("Invalid value for `institution`, must not be `None`")
        self._institution = institution

    @property
    def years(self):
        """Gets the years of this AuthorAffiliations.
        Years affiliated with this institution
        :return: The years of this AuthorAffiliations.
        :rtype: list[int].
        """
        return self._years

    @years.setter
    def years(self, years):
        """Sets the years of this AuthorAffiliations.
        Years affiliated with this institution
        :param years: The years of this AuthorAffiliations.
        :type: list[int].
        """
        if years is None:
            raise ValueError("Invalid value for `years`, must not be `None`")
        self._years = years

    def to_dict(self):
        """Returns the model properties as a dict."""
        result = {}
        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(AuthorAffiliations, dict):
            for key, value in self.items():
                result[key] = value
        return result

    def to_str(self):
        """Returns the string representation of the model."""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`."""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal."""
        if not isinstance(other, AuthorAffiliations):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal."""
        return not self == other
