"""OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git.
"""

import pprint

import six


class AuthorIds:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "openalex": "str",
        "orcid": "str",
        "scopus": "str",
        "twitter": "str",
        "wikipedia": "str",
    }
    attribute_map = {
        "openalex": "openalex",
        "orcid": "orcid",
        "scopus": "scopus",
        "twitter": "twitter",
        "wikipedia": "wikipedia",
    }

    def __init__(
        self, openalex=None, orcid=None, scopus=None, twitter=None, wikipedia=None
    ):
        """AuthorIds - a model defined in Swagger."""
        self._openalex = None
        self._orcid = None
        self._scopus = None
        self._twitter = None
        self._wikipedia = None
        self.discriminator = None
        self.openalex = openalex
        if orcid is not None:
            self.orcid = orcid
        if scopus is not None:
            self.scopus = scopus
        if twitter is not None:
            self.twitter = twitter
        if wikipedia is not None:
            self.wikipedia = wikipedia

    @property
    def openalex(self):
        """Gets the openalex of this AuthorIds.
        :return: The openalex of this AuthorIds.
        :rtype: str.
        """
        return self._openalex

    @openalex.setter
    def openalex(self, openalex):
        """Sets the openalex of this AuthorIds.
        :param openalex: The openalex of this AuthorIds.
        :type: str.
        """
        if openalex is None:
            raise ValueError("Invalid value for `openalex`, must not be `None`")
        self._openalex = openalex

    @property
    def orcid(self):
        """Gets the orcid of this AuthorIds.
        :return: The orcid of this AuthorIds.
        :rtype: str.
        """
        return self._orcid

    @orcid.setter
    def orcid(self, orcid):
        """Sets the orcid of this AuthorIds.
        :param orcid: The orcid of this AuthorIds.
        :type: str.
        """
        self._orcid = orcid

    @property
    def scopus(self):
        """Gets the scopus of this AuthorIds.
        :return: The scopus of this AuthorIds.
        :rtype: str.
        """
        return self._scopus

    @scopus.setter
    def scopus(self, scopus):
        """Sets the scopus of this AuthorIds.
        :param scopus: The scopus of this AuthorIds.
        :type: str.
        """
        self._scopus = scopus

    @property
    def twitter(self):
        """Gets the twitter of this AuthorIds.
        :return: The twitter of this AuthorIds.
        :rtype: str.
        """
        return self._twitter

    @twitter.setter
    def twitter(self, twitter):
        """Sets the twitter of this AuthorIds.
        :param twitter: The twitter of this AuthorIds.
        :type: str.
        """
        self._twitter = twitter

    @property
    def wikipedia(self):
        """Gets the wikipedia of this AuthorIds.
        :return: The wikipedia of this AuthorIds.
        :rtype: str.
        """
        return self._wikipedia

    @wikipedia.setter
    def wikipedia(self, wikipedia):
        """Sets the wikipedia of this AuthorIds.
        :param wikipedia: The wikipedia of this AuthorIds.
        :type: str.
        """
        self._wikipedia = wikipedia

    def to_dict(self):
        """Returns the model properties as a dict."""
        result = {}
        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(AuthorIds, dict):
            for key, value in self.items():
                result[key] = value
        return result

    def to_str(self):
        """Returns the string representation of the model."""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`."""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal."""
        if not isinstance(other, AuthorIds):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal."""
        return not self == other
