"""OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git.
"""

import pprint

import six


class Grant:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"funder": "str", "funder_display_name": "str", "award_id": "str"}
    attribute_map = {
        "funder": "funder",
        "funder_display_name": "funder_display_name",
        "award_id": "award_id",
    }

    def __init__(self, funder=None, funder_display_name=None, award_id=None):
        """Grant - a model defined in Swagger."""
        self._funder = None
        self._funder_display_name = None
        self._award_id = None
        self.discriminator = None
        self.funder = funder
        if funder_display_name is not None:
            self.funder_display_name = funder_display_name
        if award_id is not None:
            self.award_id = award_id

    @property
    def funder(self):
        """Gets the funder of this Grant.
        The funder OpenAlex ID
        :return: The funder of this Grant.
        :rtype: str.
        """
        return self._funder

    @funder.setter
    def funder(self, funder):
        """Sets the funder of this Grant.
        The funder OpenAlex ID
        :param funder: The funder of this Grant.
        :type: str.
        """
        if funder is None:
            raise ValueError("Invalid value for `funder`, must not be `None`")
        self._funder = funder

    @property
    def funder_display_name(self):
        """Gets the funder_display_name of this Grant.
        The funder display name
        :return: The funder_display_name of this Grant.
        :rtype: str.
        """
        return self._funder_display_name

    @funder_display_name.setter
    def funder_display_name(self, funder_display_name):
        """Sets the funder_display_name of this Grant.
        The funder display name
        :param funder_display_name: The funder_display_name of this Grant.
        :type: str.
        """
        self._funder_display_name = funder_display_name

    @property
    def award_id(self):
        """Gets the award_id of this Grant.
        The award ID
        :return: The award_id of this Grant.
        :rtype: str.
        """
        return self._award_id

    @award_id.setter
    def award_id(self, award_id):
        """Sets the award_id of this Grant.
        The award ID
        :param award_id: The award_id of this Grant.
        :type: str.
        """
        self._award_id = award_id

    def to_dict(self):
        """Returns the model properties as a dict."""
        result = {}
        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(Grant, dict):
            for key, value in self.items():
                result[key] = value
        return result

    def to_str(self):
        """Returns the string representation of the model."""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`."""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal."""
        if not isinstance(other, Grant):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal."""
        return not self == other
