"""OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git.
"""

import pprint

import six


class InstitutionIds:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "openalex": "str",
        "ror": "str",
        "grid": "str",
        "wikipedia": "str",
        "wikidata": "str",
        "mag": "int",
    }
    attribute_map = {
        "openalex": "openalex",
        "ror": "ror",
        "grid": "grid",
        "wikipedia": "wikipedia",
        "wikidata": "wikidata",
        "mag": "mag",
    }

    def __init__(
        self,
        openalex=None,
        ror=None,
        grid=None,
        wikipedia=None,
        wikidata=None,
        mag=None,
    ):
        """InstitutionIds - a model defined in Swagger."""
        self._openalex = None
        self._ror = None
        self._grid = None
        self._wikipedia = None
        self._wikidata = None
        self._mag = None
        self.discriminator = None
        self.openalex = openalex
        if ror is not None:
            self.ror = ror
        if grid is not None:
            self.grid = grid
        if wikipedia is not None:
            self.wikipedia = wikipedia
        if wikidata is not None:
            self.wikidata = wikidata
        if mag is not None:
            self.mag = mag

    @property
    def openalex(self):
        """Gets the openalex of this InstitutionIds.
        :return: The openalex of this InstitutionIds.
        :rtype: str.
        """
        return self._openalex

    @openalex.setter
    def openalex(self, openalex):
        """Sets the openalex of this InstitutionIds.
        :param openalex: The openalex of this InstitutionIds.
        :type: str.
        """
        if openalex is None:
            raise ValueError("Invalid value for `openalex`, must not be `None`")
        self._openalex = openalex

    @property
    def ror(self):
        """Gets the ror of this InstitutionIds.
        :return: The ror of this InstitutionIds.
        :rtype: str.
        """
        return self._ror

    @ror.setter
    def ror(self, ror):
        """Sets the ror of this InstitutionIds.
        :param ror: The ror of this InstitutionIds.
        :type: str.
        """
        self._ror = ror

    @property
    def grid(self):
        """Gets the grid of this InstitutionIds.
        :return: The grid of this InstitutionIds.
        :rtype: str.
        """
        return self._grid

    @grid.setter
    def grid(self, grid):
        """Sets the grid of this InstitutionIds.
        :param grid: The grid of this InstitutionIds.
        :type: str.
        """
        self._grid = grid

    @property
    def wikipedia(self):
        """Gets the wikipedia of this InstitutionIds.
        :return: The wikipedia of this InstitutionIds.
        :rtype: str.
        """
        return self._wikipedia

    @wikipedia.setter
    def wikipedia(self, wikipedia):
        """Sets the wikipedia of this InstitutionIds.
        :param wikipedia: The wikipedia of this InstitutionIds.
        :type: str.
        """
        self._wikipedia = wikipedia

    @property
    def wikidata(self):
        """Gets the wikidata of this InstitutionIds.
        :return: The wikidata of this InstitutionIds.
        :rtype: str.
        """
        return self._wikidata

    @wikidata.setter
    def wikidata(self, wikidata):
        """Sets the wikidata of this InstitutionIds.
        :param wikidata: The wikidata of this InstitutionIds.
        :type: str.
        """
        self._wikidata = wikidata

    @property
    def mag(self):
        """Gets the mag of this InstitutionIds.
        :return: The mag of this InstitutionIds.
        :rtype: int.
        """
        return self._mag

    @mag.setter
    def mag(self, mag):
        """Sets the mag of this InstitutionIds.
        :param mag: The mag of this InstitutionIds.
        :type: int.
        """
        self._mag = mag

    def to_dict(self):
        """Returns the model properties as a dict."""
        result = {}
        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(InstitutionIds, dict):
            for key, value in self.items():
                result[key] = value
        return result

    def to_str(self):
        """Returns the string representation of the model."""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`."""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal."""
        if not isinstance(other, InstitutionIds):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal."""
        return not self == other
