"""OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git.
"""

import pprint

import six


class SourceApcPrices:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"price": "int", "currency": "str"}
    attribute_map = {"price": "price", "currency": "currency"}

    def __init__(self, price=None, currency=None):
        """SourceApcPrices - a model defined in Swagger."""
        self._price = None
        self._currency = None
        self.discriminator = None
        if price is not None:
            self.price = price
        if currency is not None:
            self.currency = currency

    @property
    def price(self):
        """Gets the price of this SourceApcPrices.
        :return: The price of this SourceApcPrices.
        :rtype: int.
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this SourceApcPrices.
        :param price: The price of this SourceApcPrices.
        :type: int.
        """
        self._price = price

    @property
    def currency(self):
        """Gets the currency of this SourceApcPrices.
        :return: The currency of this SourceApcPrices.
        :rtype: str.
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this SourceApcPrices.
        :param currency: The currency of this SourceApcPrices.
        :type: str.
        """
        self._currency = currency

    def to_dict(self):
        """Returns the model properties as a dict."""
        result = {}
        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(SourceApcPrices, dict):
            for key, value in self.items():
                result[key] = value
        return result

    def to_str(self):
        """Returns the string representation of the model."""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`."""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal."""
        if not isinstance(other, SourceApcPrices):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal."""
        return not self == other
