"""OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git.
"""

import pprint

import six


class WorkIds:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "openalex": "str",
        "doi": "str",
        "mag": "int",
        "pmid": "str",
        "pmcid": "str",
    }
    attribute_map = {
        "openalex": "openalex",
        "doi": "doi",
        "mag": "mag",
        "pmid": "pmid",
        "pmcid": "pmcid",
    }

    def __init__(self, openalex=None, doi=None, mag=None, pmid=None, pmcid=None):
        """WorkIds - a model defined in Swagger."""
        self._openalex = None
        self._doi = None
        self._mag = None
        self._pmid = None
        self._pmcid = None
        self.discriminator = None
        self.openalex = openalex
        if doi is not None:
            self.doi = doi
        if mag is not None:
            self.mag = mag
        if pmid is not None:
            self.pmid = pmid
        if pmcid is not None:
            self.pmcid = pmcid

    @property
    def openalex(self):
        """Gets the openalex of this WorkIds.
        :return: The openalex of this WorkIds.
        :rtype: str.
        """
        return self._openalex

    @openalex.setter
    def openalex(self, openalex):
        """Sets the openalex of this WorkIds.
        :param openalex: The openalex of this WorkIds.
        :type: str.
        """
        if openalex is None:
            raise ValueError("Invalid value for `openalex`, must not be `None`")
        self._openalex = openalex

    @property
    def doi(self):
        """Gets the doi of this WorkIds.
        :return: The doi of this WorkIds.
        :rtype: str.
        """
        return self._doi

    @doi.setter
    def doi(self, doi):
        """Sets the doi of this WorkIds.
        :param doi: The doi of this WorkIds.
        :type: str.
        """
        self._doi = doi

    @property
    def mag(self):
        """Gets the mag of this WorkIds.
        :return: The mag of this WorkIds.
        :rtype: int.
        """
        return self._mag

    @mag.setter
    def mag(self, mag):
        """Sets the mag of this WorkIds.
        :param mag: The mag of this WorkIds.
        :type: int.
        """
        self._mag = mag

    @property
    def pmid(self):
        """Gets the pmid of this WorkIds.
        :return: The pmid of this WorkIds.
        :rtype: str.
        """
        return self._pmid

    @pmid.setter
    def pmid(self, pmid):
        """Sets the pmid of this WorkIds.
        :param pmid: The pmid of this WorkIds.
        :type: str.
        """
        self._pmid = pmid

    @property
    def pmcid(self):
        """Gets the pmcid of this WorkIds.
        :return: The pmcid of this WorkIds.
        :rtype: str.
        """
        return self._pmcid

    @pmcid.setter
    def pmcid(self, pmcid):
        """Sets the pmcid of this WorkIds.
        :param pmcid: The pmcid of this WorkIds.
        :type: str.
        """
        self._pmcid = pmcid

    def to_dict(self):
        """Returns the model properties as a dict."""
        result = {}
        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(WorkIds, dict):
            for key, value in self.items():
                result[key] = value
        return result

    def to_str(self):
        """Returns the string representation of the model."""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`."""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal."""
        if not isinstance(other, WorkIds):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal."""
        return not self == other
