"""OpenAlex API
OpenAlex is a fully open catalog of the global research system. It's named after the ancient Library of Alexandria and made by the nonprofit OurResearch.  The API is the primary way to get OpenAlex data. It's free and requires no authentication. The daily limit for API calls is 100,000 requests per user per day.  For best performance, add your email to all API requests to join the polite pool using either: - The `mailto` query parameter (e.g., `mailto=you@example.com`) - The `User-Agent` header with mailto (e.g., `User-Agent: MyApp/1.0 (mailto:you@example.com)`)  Premium users get an API key which grants higher API limits and access to special filters.
OpenAPI spec version: 1.0.0
Generated by: https://github.com/swagger-api/swagger-codegen.git.
"""

import pprint

import six


class WorkCitationNormalizedPercentile:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "value": "float",
        "is_in_top_1_percent": "bool",
        "is_in_top_10_percent": "bool",
    }
    attribute_map = {
        "value": "value",
        "is_in_top_1_percent": "is_in_top_1_percent",
        "is_in_top_10_percent": "is_in_top_10_percent",
    }

    def __init__(self, value=None, is_in_top_1_percent=None, is_in_top_10_percent=None):
        """WorkCitationNormalizedPercentile - a model defined in Swagger."""
        self._value = None
        self._is_in_top_1_percent = None
        self._is_in_top_10_percent = None
        self.discriminator = None
        if value is not None:
            self.value = value
        if is_in_top_1_percent is not None:
            self.is_in_top_1_percent = is_in_top_1_percent
        if is_in_top_10_percent is not None:
            self.is_in_top_10_percent = is_in_top_10_percent

    @property
    def value(self):
        """Gets the value of this WorkCitationNormalizedPercentile.
        :return: The value of this WorkCitationNormalizedPercentile.
        :rtype: float.
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this WorkCitationNormalizedPercentile.
        :param value: The value of this WorkCitationNormalizedPercentile.
        :type: float.
        """
        self._value = value

    @property
    def is_in_top_1_percent(self):
        """Gets the is_in_top_1_percent of this WorkCitationNormalizedPercentile.
        :return: The is_in_top_1_percent of this WorkCitationNormalizedPercentile.
        :rtype: bool.
        """
        return self._is_in_top_1_percent

    @is_in_top_1_percent.setter
    def is_in_top_1_percent(self, is_in_top_1_percent):
        """Sets the is_in_top_1_percent of this WorkCitationNormalizedPercentile.
        :param is_in_top_1_percent: The is_in_top_1_percent of this WorkCitationNormalizedPercentile.
        :type: bool.
        """
        self._is_in_top_1_percent = is_in_top_1_percent

    @property
    def is_in_top_10_percent(self):
        """Gets the is_in_top_10_percent of this WorkCitationNormalizedPercentile.
        :return: The is_in_top_10_percent of this WorkCitationNormalizedPercentile.
        :rtype: bool.
        """
        return self._is_in_top_10_percent

    @is_in_top_10_percent.setter
    def is_in_top_10_percent(self, is_in_top_10_percent):
        """Sets the is_in_top_10_percent of this WorkCitationNormalizedPercentile.
        :param is_in_top_10_percent: The is_in_top_10_percent of this WorkCitationNormalizedPercentile.
        :type: bool.
        """
        self._is_in_top_10_percent = is_in_top_10_percent

    def to_dict(self):
        """Returns the model properties as a dict."""
        result = {}
        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(WorkCitationNormalizedPercentile, dict):
            for key, value in self.items():
                result[key] = value
        return result

    def to_str(self):
        """Returns the string representation of the model."""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`."""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal."""
        if not isinstance(other, WorkCitationNormalizedPercentile):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal."""
        return not self == other
